# Generated by Django 4.2.7 on 2024-07-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
